### ISSUE TITLE
LD14 USB interface

### ISSUE THREAD

**Issue by shiba-8ro** [ldrobotSensorTeam/ldlidar_sl_ros#4]
Hi, I purchase LD14, but if I wish use your ROS package, I need purchase USB interface.
Is the USB interface correct in the image below?
![image](https://github.com/ldrobotSensorTeam/ldlidar_sl_ros/assets/5852451/8d24c868-a91f-4162-97bd-507a562296af)

**Comment by mingdonghu** [comment]
@shiba-8ro usb module select cp2102 usb to TTL uart bridge

**Comment by mingdonghu** [comment]
@shiba-8ro module picture as:
![image](https://github.com/ldrobotSensorTeam/ldlidar_sl_ros/assets/52943852/08f52040-7d2d-4a6d-b4b2-e54e1c2062b7)

**Comment by shiba-8ro** [comment]
@mingdonghu 
Grate thanks.
My team is trying using LD14 with Turtlebot3.
Because LD08 was discontinued.

**Comment by shiba-8ro** [comment]
My Issue was solved. Thanks.
